language: go

go:
    - 1.14

cache:
    directories:
        - $GOPATH/src
        - $GOPATH/pkg

install:
    - go get github.com/go-chi/chi
    - go get github.com/Urethramancer/daemon
    - go get github.com/Urethramancer/signor
